# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
# -*- encoding: utf-8 -*-
# stub: rails_current 2.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rails_current"
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Ara T. Howard"]
  s.date = "2018-02-07"
  s.description = "track `current_user` et all in a tidy, global, and thread-safe fashion."
  s.email = "ara.t.howard@gmail.com"
  s.extra_rdoc_files = ["Manifest.txt", "README.md"]
  s.files = ["Manifest.txt", "README.md", "Rakefile", "lib/rails_current.rb", "tasks/default.rake", "tasks/this.rb", "test/rails_current_test.rb", "test/testing.rb"]
  s.homepage = "https://github.com/ahoward/rails_current"
  s.licenses = ["Ruby"]
  s.rdoc_options = ["--main", "README.md", "--markup", "tomdoc"]
  s.required_ruby_version = Gem::Requirement.new(">= 2.2.0")
  s.rubygems_version = "2.4.5.4"
  s.summary = "track `current_user` et all in a tidy, global, and thread-safe fashion."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<map>, ["~> 6.0"])
      s.add_development_dependency(%q<rake>, ["~> 10.1"])
      s.add_development_dependency(%q<minitest>, ["~> 5.0"])
    else
      s.add_dependency(%q<map>, ["~> 6.0"])
      s.add_dependency(%q<rake>, ["~> 10.1"])
      s.add_dependency(%q<minitest>, ["~> 5.0"])
    end
  else
    s.add_dependency(%q<map>, ["~> 6.0"])
    s.add_dependency(%q<rake>, ["~> 10.1"])
    s.add_dependency(%q<minitest>, ["~> 5.0"])
  end
end
